### ISSUE TITLE
Include the prefix `http://` or `https://` in the Image URL

### ISSUE THREAD

**Issue by jonaprieto** [parpalak/i.upmath.me#4]
The image URL needs to include the prefixes mentioned in the title of this issue.
Consider that copy such URLs do not work in Markdown files.

Just using an inline style:

```Markdown
![fx](//tex.s2cms.ru/png/f(x))
```
renders to

![fx](//tex.s2cms.ru/png/f(x))

Instead of:

![fx](http://tex.s2cms.ru/png/f(x))

by prepending the http:// prefix

```Markdown
![fx](http://tex.s2cms.ru/png/f(x))
```

**Comment by parpalak** [comment]
Actually the URL scheme may be omitted and such scheme-agnostic URLs are perfectly valid: https://stackoverflow.com/questions/9161769/url-without-httphttps
However, some markdown parsers (including Github) fail to detect them.

I could add the "https:" prefix for generated image URLs in the interface. But it would result in dropping old user agents without SNI (https://caniuse.com/#search=sni) if the "https" link appears on a "http" website. That's why I choose scheme-agnostic URLs for http://tex.s2cms.com/

**Comment by jonaprieto** [comment]
Ok. Maybe adding an option to choose.
